version: '3.1'
services:
  app:
    image: app2  
    ports:
    - '8000:8000'
    command: bash -c "python manage.py runserver 0.0.0.0:8000"


  frontend:
    image: web1
    ports:
    - "3000:3000"
